// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShackProfiles.Data;

namespace ShackProfiles.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("ShackProfiles.Models.ShackProfile", b =>
                {
                    b.Property<string>("Shackname")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BattlenetId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("DiscordId");

                    b.Property<string>("EpicGamesId");

                    b.Property<string>("NintendoId");

                    b.Property<string>("OriginId");

                    b.Property<string>("PSNName");

                    b.Property<string>("SteamName");

                    b.Property<string>("SteamUrl");

                    b.Property<string>("TimeZone");

                    b.Property<string>("UplayId");

                    b.Property<bool>("Verified");

                    b.Property<string>("XboxGamertag");

                    b.HasKey("Shackname");

                    b.ToTable("ShackProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
